stages:
  - test

image: node:20

cache:
  paths:
    - node_modules/

unit_tests:
  stage: test
  script:
    - echo "Hello World!"
    - echo $COSTAM
    - echo "================================"
    - npm ci
    - make test-unit
  artifacts:
    when: always
    paths:
      - logs/test-report.html
      - logs/test-report.json
    expire_in: 1 week
