stages:
  - test

image: node:20

cache:
  paths:
    - node_modules/

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: user
  MYSQL_PASSWORD: user
  MYSQL_DATABASE: air_book

unit_tests:
  stage: test
  script:
    - echo "Hello World!"
    - echo "=== Zmienne środowiskowe ==="
    - echo $MYSQL_ROOT_PASSWORD
    - echo "================================"
    - npm ci
    - make test-unit
  artifacts:
    when: always
    paths:
      - logs/test-report.html
      - logs/test-report.json
    expire_in: 1 week
