openapi: 3.0.0
info:
  title: Air-Book API
  version: 1.0.0
  description: API documentation for the Air-Book application

servers:
  - url: http://localhost:3000

paths:
  /healthCheck/postgresHealth:
    $ref: './healthCheck.yaml#/postgresHealth'
  /healthCheck/neo4jHealth:
    $ref: './healthCheck.yaml#/neo4jHealth'

  /register:
    $ref: './register.yaml'

  /login:
    $ref: './login.yaml'

  /refreshToken:
    $ref: './refreshToken.yaml'

  /logout:
    $ref: './logout.yaml'

  /airport/getAllAirports:
    $ref: './airport.yaml#/getAllAirports'
  /flight/getAllFlights:
    $ref: './flight.yaml#/getAllFlights'
  /flight/searchFlights:
    $ref: './flight.yaml#/searchFlights'
  /flight/getFlightsByIds:
    $ref: './flight.yaml#/getFlightsByIds'
  /flight/getFlightsByUserId/{userId}:
    $ref: './flight.yaml#/getFlightsByUserId'
  /flight/patchFlightById/{flightId}:
    $ref: './flight.yaml#/patchFlightById'

  /user/getAllUsers:
    $ref: './user.yaml#/getAllUsers'
  /user/getUserById/{userId}:
    $ref: './user.yaml#/getUserById'
  /user/getNotificationsByUserId/{userId}:
    $ref: './user.yaml#/getNotificationsByUserId'
  /user/createNewUser:
    $ref: './user.yaml#/createNewUser'
  /user/updateUserById/{userId}:
    $ref: './user.yaml#/updateUserById'
  /user/patchUserById/{userId}:
    $ref: './user.yaml#/patchUserById'
  /user/deleteUserById/{userId}:
    $ref: './user.yaml#/deleteUserById'
  /user/createNotification:
    $ref: './user.yaml#/createNotification'
  /user/createReservation:
    $ref: './user.yaml#/createReservation'
  /user/deleteReservationById/{reservationId}:
    $ref: './user.yaml#/deleteReservationById'


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
