apiVersion: 1

datasources:
  - name: DS_PROMETHEUS
    type: prometheus
    url: http://prometheus:9090

  - name: DS_LOKI
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      maxLines: 1000
